/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cellState_CONSTANTS_H
#define cellState_CONSTANTS_H

#include "cellState_types.h"



class cellStateConstants {
 public:
  cellStateConstants();

};

extern const cellStateConstants g_cellState_constants;



#endif
