/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "cellState_constants.h"



const cellStateConstants g_cellState_constants;

cellStateConstants::cellStateConstants() {
}



