/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cell_CONSTANTS_H
#define cell_CONSTANTS_H

#include "cell_types.h"



class cellConstants {
 public:
  cellConstants();

};

extern const cellConstants g_cell_constants;



#endif
