/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef gameState_CONSTANTS_H
#define gameState_CONSTANTS_H

#include "gameState_types.h"



class gameStateConstants {
 public:
  gameStateConstants();

};

extern const gameStateConstants g_gameState_constants;



#endif
