/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "gameState_constants.h"



const gameStateConstants g_gameState_constants;

gameStateConstants::gameStateConstants() {
}



